version: '3.8'

networks:
  dappstp-net:
    driver: bridge

volumes:
  db_data:
  grafana-data: {}

services:
  postgres:
    image: postgres:15
    container_name: dappstp-db
    environment:
      POSTGRES_DB: dappstp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5233:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - dappstp-net

  redis:
    image: redis:alpine
    container_name: dappstp-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - dappstp-net

  dappstp-app:
    build:
      context: ./dappstp # El contexto apunta a la carpeta de tu app
      dockerfile: Dockerfile
    container_name: dappstp-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: dappstp
      DB_USER: postgres
      DB_PASS: postgres
      SPRING_DATA_REDIS_HOST: redis
    shm_size: '2gb'
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - dappstp-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    restart: unless-stopped
    networks:
      - dappstp-net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - dappstp-net
