name: Monitoring Setup Placeholder

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display message
        run: echo "This workflow is a placeholder and does not deploy the monitoring stack."

