name: Deploy to Render

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-cvrjd5ggjchc73bb5vtg?key=2ECYUubyzcQ